server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000

spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: a5268413
    url: jdbc:mysql:///cfx
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  resources:
    static-locations: classpath:/META_INF/resources/,classpath:/META-INF/resources/webjars/
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.springboot.md.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
